//==============================================================================
// MusicState.h
// Created 2014-08-12
//==============================================================================

#ifndef MUSICSTATE
#define MUSICSTATE

#include <stdint.h>
#include "Random.h"

/*
 * Encapsulates all signals that are generated by the audio analysis tools
 * and used by the light pattern generation tools.
 */

//------------------------------------------------------------------------------
class MusicState {
public:
  volatile uint16_t const* spectrum; // full spectral info
  unsigned sample;  // last hfc sample considered when calculated features
  unsigned hfc;     // HFC content (averaged over some number of windows)
  unsigned samplesSinceOnset; // 0 means this moment is an onset
  unsigned onsetSignificance; // number of standard deviations above the mean at beginning of onset
  unsigned maxSignificance;   // max standard deviations above the mean during onset
  unsigned beat;    // number of the beat in the curent beat train
  unsigned beatpos; // beat subposition in [0, 1024)
  mutable XorShift32 rand;
public:
  // random number based on spectral information
  unsigned random () const;
  // linearly scaled version of hfc signal
  unsigned hfcLin (unsigned scale) const;
  // logarithmically scaled version of hfc signal
  unsigned hfcLog (unsigned scale, unsigned noise_floor = 1150) const;
  // sawtooth wave that rises abruptly at onsets, and decays linearly
  unsigned onsetSaw (unsigned scale, unsigned decay, bool useMaxSignificance = false) const;
};

class SawDecay {
public:
  unsigned lastSample;
  unsigned lastHeight;
  unsigned currentHeight;
  unsigned decayFall;
  unsigned decayTime;
public:
  SawDecay (unsigned df, unsigned dt): lastSample(0), lastHeight(0), currentHeight(0), decayFall(df), decayTime(dt) {}
  void update (unsigned sample, unsigned height);
  inline unsigned height () const {
    return currentHeight;
  }
};

template <unsigned N>
class FlickerFeature {
public:
  unsigned sample;
  unsigned timescale;
  int scale;
  int step;  
  int correlation;
  int16_t value[N]; 
public:
  FlickerFeature (): sample(0), timescale(4), scale(512), step(33), correlation(185) { memset(value, 0, N*sizeof(int16_t)); }
  void update (MusicState const& state);
  int height (unsigned x) const { return value[x]; } 
};

template <unsigned N>
void FlickerFeature<N>::update (MusicState const& state) {
  if (state.sample >= sample + timescale) {
    sample = state.sample;
    int temp;
    for (unsigned x=0; x<N; ++x) {
      unsigned random_uint = state.rand.uint32();
      int random_int = (random_uint % (2 * scale)) - scale;
      if (random_int > value[x]) {
        temp = value[x] + step;
        value[x] = (temp > 0x7FFF) ? 0x7FFF : temp;
      } else if (random_int < value[x]) {
        temp = value[x] - step;
        value[x] = (temp < -0x8000) ? -0x8000 : temp;
      }
    }
    for (unsigned x=0; x<N; ++x) {
      int sum = 0;
      sum += value[(x + N - 2) % N];
      sum += value[(x + N - 1) % N];
      sum += value[x];
      sum += value[(x + 1) % N];
      sum += value[(x + 2) % N];
      value[x] = (correlation * sum / 5 + (256 - correlation) * value[x]) / 256;
    }
  }
}


//==============================================================================
// Log2
//==============================================================================

//------------------------------------------------------------------------------
uint16_t log2_fp (uint16_t x_16t);

#endif

