//==============================================================================
// MusicState.h
// Created 2014-08-12
//==============================================================================

#ifndef MUSICSTATE
#define MUSICSTATE

#include <stdint.h>

/*
 * Encapsulates all signals that are generated by the audio analysis tools
 * and used by the light pattern generation tools.
 */

//------------------------------------------------------------------------------
class MusicState {
public:
  volatile uint16_t const* spectrum; // full spectral info
  unsigned id;      // simply an incrementing counter
  unsigned hfc;     // HFC content (averaged over some number of windows)
  unsigned samplesSinceOnset; // 0 means this moment is an onset
  unsigned onsetSignificance; // number of standard deviations above the mean
  unsigned beat;    // number of the beat in the curent beat train
  unsigned beatpos; // beat subposition in [0, 1024)
public:
  unsigned random () const;
};

#endif
